#!/bin/bash

DIR=$(cd $(dirname $0); pwd)
TEXT=$(cat)
COMMAND="echo '${TEXT}' | juman $@"

docker-compose \
  -f ${DIR}/../japanese/docker-compose.yml \
  run --rm juman_knp sh --login \
  -c "${COMMAND}"
